name: UHC_Core
version: ${project.version}
main: me.ofearr.uhccore.UHCCore
commands:
  start-uhc:
    description: Starts a game of UHC.
    aliases:
      - uhc-start
      - startuhc
      - uhcstart
  end-uhc:
    description: Starts a game of UHC.
    aliases:
      - uhc-end
      - enduhc
      - uhcend
  giveenchant:
    description: Gives the specified player the specified enchant.
    aliases:
      - givecustomenchant
  teamchat:
    description: Allows team members to send messages that only their team can see!
    aliases: [tc, teamc, privatechat, uhcchat]
